### ISSUE TITLE
File handlers

### ISSUE THREAD

**Issue by DmitryKutsev** [DmitryKutsev/petukhon_study#1]
Вы договариваетесь о названии ветки, и кто-то один (ну, кто первый начнет, вероятно) делает ветку. 

Там должен лежать ОДНИН на всех файл "log.txt" и питоновский файл, названный вашим именем, в котором будет функция, добавляющая в этот файл строку. 
Функция должна принимать строку и записывать в файл эту строку в формате:
"Текущая дата и время записи в лог" + "строка, которую передали в функцию"

Попробуйте договориться так, чтобы в файле в репозитории было по 1 строке на человека. 
Т.е. первый кто создал ветку создает и файл, пишет функцией туда свою строку, пушит.

Потом следующий делает гит пулл, дописывает в файл свою строку, пушит

**Comment by DmitryKutsev** [comment]
Номер этой задачи - #1 (это видно наверху). Чтобы в этой задаче отображались ваши коммиты, добавляйте в комментарий коммита "#1" в конец.
например:

git commit -a -m "Created the log.txt file, wrote an init string. #1"

**Comment by Koryakova** [comment]
Ветка создана, называется file_branch. Файл "log.txt"  с которым нужно работать лежит в ней.
